#!/usr/bin/env python3
"""Generate content/content.js from the markdown tree in content/docs.

The site (learn.html) renders markdown client-side; embedding the page text
in a JS file lets it work from file:// and GitHub Pages alike, with no
server or build framework needed.

Run from the repo root whenever content/docs changes:

    python tools/build_content.py
"""

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = REPO_ROOT / "content"
DOCS_DIR = CONTENT_DIR / "docs"
OUT_FILE = CONTENT_DIR / "content.js"

# Tolerates a missing trailing newline after the closing --- and front matter
# wrapped in an HTML comment (both occur in the MakerLabs26 source files).
FRONT_MATTER_RE = re.compile(
    r"\A(?:<!--\s*)?---\s*\n(.*?)\n---\s*(?:-->)?[ \t]*(?:\n|\Z)", re.DOTALL
)


def parse_front_matter(text):
    """Return (meta dict, body) for a markdown file."""
    meta = {}
    m = FRONT_MATTER_RE.match(text)
    if not m:
        return meta, text
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        value = value.strip().strip('"').strip("'")
        meta[key.strip()] = value
    return meta, text[m.end():]


def main():
    pages = {}
    for path in sorted(DOCS_DIR.rglob("*.md")):
        rel = path.relative_to(CONTENT_DIR).as_posix()
        text = path.read_text(encoding="utf-8")
        meta, body = parse_front_matter(text)

        if meta.get("draft", "").lower() in {"true", "yes", "1"}:
            continue

        try:
            order = int(meta.get("nav_order", "999"))
        except ValueError:
            order = 999

        pages[rel] = {
            "title": meta.get("title") or path.stem,
            "parent": meta.get("parent") or None,
            "order": order,
            "body": body.strip(),
        }

    payload = json.dumps({"pages": pages}, ensure_ascii=False, indent=None)
    OUT_FILE.write_text(
        "// GENERATED by tools/build_content.py — do not edit by hand.\n"
        "// Edit the markdown in content/docs/ and rerun the script.\n"
        f"window.SITE_CONTENT = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT_FILE.relative_to(REPO_ROOT)} with {len(pages)} pages.")


if __name__ == "__main__":
    main()
